#!/bin/bash
#   ANSI CODE   ##################################################################
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
Yellow='\033[1;33m'
White='\033[1;37m'
NC='\033[0m'
###################################################################


# Create a temporary script file
TMP_SCRIPT=$(mktemp /tmp/countdown_script.XXXXXX)
cat << 'EOL' > "$TMP_SCRIPT"
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
Yellow='\033[1;33m'
White='\033[1;37m'






#!/bin/bash
tput civis
ggg=$(wmctrl -l |grep Terminal|tail -n1|awk '{print $1}')
toggle-decorations $ggg
clear
echo -e ${Blue}'+--------------------------------------------------+'
echo -e ${NC}
sudo apt-get autoremove --purge
tput cup 3 15
echo -e ${Purple}" Running autoremove"
tput cup 3 0
tput el

sudo apt-get autoclean
tput cup 3 15
echo -e ${Purple}" Running autoclean"
tput cup 3 0
tput el

sudo apt-get clean
flatpak uninstall --unused
tput cup 3 15
echo -e ${Purple}" Running flatpak uninstall"
tput cup 3 0
tput el

yt-dlp --rm-cache-dir
tput cup 3 15
rm -r /home/batan/.cache/mozilla/firefox/*
tput cup 3 15
sudo find /home/*/.local/share/Trash -mindepth 1 -exec rm -r {} \;
sudo rm /var/log/unattended-upgrades/unattended-upgrades-shutdown.log
for i in $(sudo ls -a /var/cache/apt/archives/partial/);do sudo rm $i;done
sudo find /var/log -type f -exec rm -r {} \;


iii=$(find /home/batan/.cache/thumbnails/ -type f -name '*.png'|wc -l)
clear
echo -e ${Cyan}"################################################"

tput cup 5 0
echo -e ${Cyan}  "################################################"
tput cup 2 13
echo -e ${Yellow}"Thumnails to shred:"
tput cup 3 22
for i in $(find /home/batan/.cache/thumbnails/ -type f -name '*.png')
do
tput cup 3 22
echo -e ${White}$iii
shred -z -u -n 1 $i
(( iii -= 1 ))
tput cup 3 0
tput el
done
clear

echo 1|sudo tee /proc/sys/vm/drop_caches
echo 2|sudo tee /proc/sys/vm/drop_caches
echo 3|sudo tee /proc/sys/vm/drop_caches

sudo sweeper --automatic
sudo bleachbit -preset -c
mkdir ~/.cache/calendar.vim/ && cp ~/dot/credentials.vim ~/.cache/calendar.vim/
sudo -a swappoff
sudo -a swapon
clear
echo -e 'DONE'
read -n1 -p 'Press [Any] to Finish...' xxx
EOL
/usr/bin/xfce4-terminal --hide-menubar --hide-scrollbar --geometry="60x8-0+0" -e "sudo -u batan bash $TMP_SCRIPT"
